stages:
  - build
  - deploy
build_site:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - build
  only:
    - master

deploy_production:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync build/ s3://pulse-realtime-api/ --delete --cache-control max-age=31557600,public
  only:
    - master
